name: Mirror Yambar Repo

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight
  workflow_dispatch:  # Allows manual triggering

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Codeberg repository
        run: |
          git clone --mirror https://codeberg.org/dnkl/yambar.git repo
          
      - name: Fetch changes from GitHub (mirror update)
        run: |
          cd repo
          git fetch origin

      - name: Checkout the main branch
        run: |
          cd repo
          git checkout --force main

      - name: Merge Codeberg updates into main branch
        run: |
          cd repo
          git merge origin/main || echo "No changes to merge"

      - name: Protect workflow branch
        run: |
          cd repo
          git fetch origin workflow-branch:workflow-branch

      - name: Push changes to main (without affecting workflow branch)
        run: |
          cd repo
          git remote set-url --push origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/kzwkt/yambar.git
          git push origin main

      - name: Push workflow branch if needed (e.g., update workflows)
        run: |
          cd repo
          git push origin workflow-branch
