name: Mirror Yambar Repo

on:
  push:
    branches:
      - workflow-only  # Trigger only on pushes to the 'workflow-only' branch
  schedule:
    - cron: '0 0 * * *'  # Run every day at midnight (UTC)

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Codeberg repository
        run: |
          git clone https://codeberg.org/dnkl/yambar.git repo

      - name: Fetch changes from Codeberg
        run: |
          cd repo
          git fetch origin

      - name: Merge Codeberg updates into master branch
        run: |
          cd repo
          git checkout master  # Change 'main' to 'master'
          git merge origin/master || echo "No changes to merge"  # Change 'main' to 'master'

      - name: Push changes to GitHub
        run: |
          cd repo
          git remote set-url --push origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/kzwkt/yambar.git
          git push origin master  # Change 'main' to 'master'
