name: Mirror Yambar Repo

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight
  workflow_dispatch:  # Allows manual triggering

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Codeberg repository
        run: |
          git clone https://codeberg.org/dnkl/yambar.git repo

      - name: Fetch changes from Codeberg
        run: |
          cd repo
          git fetch origin

      - name: Merge Codeberg updates into main branch
        run: |
          cd repo
          git checkout main
          git merge origin/main || echo "No changes to merge"

      - name: Push changes to GitHub
        run: |
          cd repo
          git remote set-url --push origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/kzwkt/yambar.git
          git push origin main
